[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "attendance-manager"  # Nazwa projektu, zastąp odpowiednią
version = "0.1.0"  # Pierwsza wersja
description = "A Python application for managing attendance and student data."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}  # Zmień na swoje dane
]
dependencies = [
    "pandas>=1.0",  # Dodaj wszystkie wymagane zależności
    "numpy",
]

[tool.setuptools]
packages = ["dist"]  # Zmień na odpowiednią ścieżkę jeśli Twoje moduły są w innym katalogu
include_package_data = true

[tool.setuptools.package-data]
"*": ["*.csv"]  # Jeśli potrzebujesz dołączyć dane CSV

[tool.setuptools.scripts]
main = "dist.main:main"  # Zmień, jeśli Twój główny punkt wejścia jest inny
